# version: "3.9"
services:
  db:
    image: postgres:alpine
    container_name: fs4t-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fs4t_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  bot:
    build: ./bot
    container_name: fs4t-bot
    restart: always
    depends_on:
      - db
    env_file:
      - ./bot/.env
    volumes:
      - ./bot/.env:/app/bot/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/fs4t_db
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4