# image Node.js
FROM node:22-alpine

# working directory in container
WORKDIR /usr/src/app

# copy the configuration file
COPY package*.json ./

# install dependency with retry and timeout settings
RUN npm install
RUN npm install dotenv
RUN npm install googleapis
RUN npm install discord.js
RUN npm install express
RUN npm install open
RUN npm install pg

# copy all source code
COPY . .

# Expose port (optional, for OAuth server)
EXPOSE 3000

# run
CMD ["node", "index.js"]
