# image Node.js
FROM node:22-alpine

# working directory in container
WORKDIR /usr/src/app

# copy package files first for better caching
COPY package*.json ./

# install dependencies
RUN npm install --omit=dev --no-audit --no-fund

# copy all source code
COPY . .

# Expose port for OAuth server
EXPOSE 3000

# run the application
CMD ["node", "index.js"]
